apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: ditto-ui
  name: ditto-ui
  namespace: ditto
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ditto-ui
  template:
    metadata:
      labels:
        component: ditto-ui
    spec:
      containers:
        - image: sanjoydeb0007/ditto-test-argocd:v1
          name: ditto-ui
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ditto-ui
