apiVersion: v1
kind: Service
metadata:
  labels:
    component: ditto-ui
  name: ditto-ui
  namespace: ditto
spec:
  ports:
    - name: ditto-ui
      nodePort: 30001
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: ditto-ui
  type: NodePort
